import 'dart:ui';
import '../models/level.dart';

class LevelsData {
  static const int freeLevelCount = 3;
  static const String premiumProductId = 'jumper_premium_levels';

  static final List<GameLevel> levels = [
    // === FREE LEVELS ===
    GameLevel(
      id: 1,
      name: 'Green Meadows',
      description: 'A peaceful beginning in the sunny meadows',
      isFree: true,
      primaryColor: Color(0xFF4CAF50),
      secondaryColor: Color(0xFF81C784),
      backgroundTheme: 'meadow',
      gravity: 900,
      jumpForce: -520,
      targetScore: 500,
      totalPlatforms: 25,
      levelHeight: 4000,
      platformConfigs: [
        PlatformConfig(type: PlatformType.normal, probability: 1.0),
      ],
    ),
    GameLevel(
      id: 2,
      name: 'Crystal Caves',
      description: 'Explore the sparkling underground caverns',
      isFree: true,
      primaryColor: Color(0xFF7C4DFF),
      secondaryColor: Color(0xFFB388FF),
      backgroundTheme: 'cave',
      gravity: 920,
      jumpForce: -530,
      targetScore: 800,
      totalPlatforms: 28,
      levelHeight: 4500,
      platformConfigs: [
        PlatformConfig(type: PlatformType.normal, probability: 0.8),
        PlatformConfig(type: PlatformType.moving, probability: 0.2),
      ],
    ),
    GameLevel(
      id: 3,
      name: 'Sunset Peaks',
      description: 'Climb the mountains at golden hour',
      isFree: true,
      primaryColor: Color(0xFFFF7043),
      secondaryColor: Color(0xFFFFAB91),
      backgroundTheme: 'mountain',
      gravity: 940,
      jumpForce: -540,
      targetScore: 1000,
      totalPlatforms: 30,
      levelHeight: 5000,
      platformConfigs: [
        PlatformConfig(type: PlatformType.normal, probability: 0.7),
        PlatformConfig(type: PlatformType.moving, probability: 0.2),
        PlatformConfig(type: PlatformType.breakable, probability: 0.1),
      ],
    ),

    // === PREMIUM LEVELS ===
    GameLevel(
      id: 4,
      name: 'Frozen Tundra',
      description: 'Navigate the icy platforms of the north',
      requiredStars: 3,
      isFree: false,
      primaryColor: Color(0xFF00BCD4),
      secondaryColor: Color(0xFF80DEEA),
      backgroundTheme: 'ice',
      gravity: 960,
      jumpForce: -550,
      targetScore: 1200,
      totalPlatforms: 32,
      levelHeight: 5500,
      platformConfigs: [
        PlatformConfig(type: PlatformType.normal, probability: 0.6),
        PlatformConfig(type: PlatformType.moving, probability: 0.2),
        PlatformConfig(type: PlatformType.breakable, probability: 0.1),
        PlatformConfig(type: PlatformType.disappearing, probability: 0.1),
      ],
    ),
    GameLevel(
      id: 5,
      name: 'Volcano Core',
      description: 'Jump through the fiery depths of the volcano',
      requiredStars: 5,
      isFree: false,
      primaryColor: Color(0xFFF44336),
      secondaryColor: Color(0xFFEF9A9A),
      backgroundTheme: 'volcano',
      gravity: 980,
      jumpForce: -560,
      targetScore: 1500,
      totalPlatforms: 35,
      levelHeight: 6000,
      platformConfigs: [
        PlatformConfig(type: PlatformType.normal, probability: 0.5),
        PlatformConfig(type: PlatformType.moving, probability: 0.25),
        PlatformConfig(type: PlatformType.breakable, probability: 0.15),
        PlatformConfig(type: PlatformType.spring, probability: 0.1),
      ],
    ),
    GameLevel(
      id: 6,
      name: 'Cloud Kingdom',
      description: 'Bounce among the clouds in the sky kingdom',
      requiredStars: 8,
      isFree: false,
      primaryColor: Color(0xFF42A5F5),
      secondaryColor: Color(0xFF90CAF9),
      backgroundTheme: 'cloud',
      gravity: 950,
      jumpForce: -570,
      targetScore: 1800,
      totalPlatforms: 38,
      levelHeight: 6500,
      platformConfigs: [
        PlatformConfig(type: PlatformType.normal, probability: 0.4),
        PlatformConfig(type: PlatformType.moving, probability: 0.25),
        PlatformConfig(type: PlatformType.disappearing, probability: 0.2),
        PlatformConfig(type: PlatformType.spring, probability: 0.15),
      ],
    ),
    GameLevel(
      id: 7,
      name: 'Neon City',
      description: 'Cyberpunk platforms in the neon-lit city',
      requiredStars: 12,
      isFree: false,
      primaryColor: Color(0xFFE040FB),
      secondaryColor: Color(0xFFEA80FC),
      backgroundTheme: 'neon',
      gravity: 1000,
      jumpForce: -580,
      targetScore: 2000,
      totalPlatforms: 40,
      levelHeight: 7000,
      platformConfigs: [
        PlatformConfig(type: PlatformType.normal, probability: 0.35),
        PlatformConfig(type: PlatformType.moving, probability: 0.3),
        PlatformConfig(type: PlatformType.breakable, probability: 0.15),
        PlatformConfig(type: PlatformType.disappearing, probability: 0.1),
        PlatformConfig(type: PlatformType.spring, probability: 0.1),
      ],
    ),
    GameLevel(
      id: 8,
      name: 'Space Station',
      description: 'Zero-gravity jumps in outer space',
      requiredStars: 16,
      isFree: false,
      primaryColor: Color(0xFF1A237E),
      secondaryColor: Color(0xFF5C6BC0),
      backgroundTheme: 'space',
      gravity: 850,
      jumpForce: -600,
      targetScore: 2500,
      totalPlatforms: 42,
      levelHeight: 7500,
      platformConfigs: [
        PlatformConfig(type: PlatformType.normal, probability: 0.3),
        PlatformConfig(type: PlatformType.moving, probability: 0.3),
        PlatformConfig(type: PlatformType.breakable, probability: 0.15),
        PlatformConfig(type: PlatformType.disappearing, probability: 0.15),
        PlatformConfig(type: PlatformType.spring, probability: 0.1),
      ],
    ),
    GameLevel(
      id: 9,
      name: 'Dragon\'s Lair',
      description: 'The ultimate challenge in the dragon\'s domain',
      requiredStars: 20,
      isFree: false,
      primaryColor: Color(0xFFFF6F00),
      secondaryColor: Color(0xFFFFCA28),
      backgroundTheme: 'dragon',
      gravity: 1050,
      jumpForce: -620,
      targetScore: 3000,
      totalPlatforms: 45,
      levelHeight: 8000,
      platformConfigs: [
        PlatformConfig(type: PlatformType.normal, probability: 0.25),
        PlatformConfig(type: PlatformType.moving, probability: 0.3),
        PlatformConfig(type: PlatformType.breakable, probability: 0.2),
        PlatformConfig(type: PlatformType.disappearing, probability: 0.15),
        PlatformConfig(type: PlatformType.spring, probability: 0.1),
      ],
    ),
    GameLevel(
      id: 10,
      name: 'The Void',
      description: 'A mysterious dimension with endless darkness',
      requiredStars: 25,
      isFree: false,
      primaryColor: Color(0xFF212121),
      secondaryColor: Color(0xFF616161),
      backgroundTheme: 'void',
      gravity: 1100,
      jumpForce: -640,
      targetScore: 4000,
      totalPlatforms: 50,
      levelHeight: 9000,
      platformConfigs: [
        PlatformConfig(type: PlatformType.normal, probability: 0.2),
        PlatformConfig(type: PlatformType.moving, probability: 0.3),
        PlatformConfig(type: PlatformType.breakable, probability: 0.2),
        PlatformConfig(type: PlatformType.disappearing, probability: 0.2),
        PlatformConfig(type: PlatformType.spring, probability: 0.1),
      ],
    ),
  ];

  static bool isLevelFree(int levelId) {
    return levelId <= freeLevelCount;
  }

  static GameLevel getLevel(int levelId) {
    return levels.firstWhere(
      (level) => level.id == levelId,
      orElse: () => levels.first,
    );
  }
}
